---
- name: Reset blockchain data!
  hosts: all
  gather_facts: true

  roles:
    - role: decimal-service
      vars:
        srv_mode: stop

    - role: decimal-init
      vars:
        mode: '{{ mode }}' # external variable: mode = master | slave

    - role: decimal-service
      vars:
        srv_mode: start
