---
- name: Stop explorer indexer process
  shell: pm2 stop all

- name: Drop schema "public" with cascade
  postgresql_schema:
    db: ordererdev
    name: public
    state: absent
    cascade_drop: true
  become: true
  become_user: postgres

- name: Create schema "public"
  postgresql_schema:
    db: ordererdev
    name: public
    owner: ordererdev
    state: present
  become: true
  become_user: postgres

- name: Start explorer indexer process
  shell: pm2 start all  